Question_list: 
  - 본인의 나이를 입력해주세요.
  - 자녀의 나이를 입력해주세요.
  - 당신의 하루 평균 수명 시간은 얼마인가요?
  - 당신의 하루 평균 이동 시간은 얼마인가요?
  - 당신의 일주일간 노동 시간은 얼마인가요?
  - 운동, 부모 개인 시간, 미디어 기기 사용시간 등 당신의 일주일간 여가 시간은 얼마인가요?
  - 일주일간 자녀와 함께하는 시간은 어느정도인가요?