Question_list: 
  - 본인의 나이를 입력해주세요.
  - 자녀의 나이를 입력해주세요.
  - 당신의 하루 평균 수면 시간은 몇시간인가요?
  - 당신의 하루 평균 이동 시간은 몇분인가요?
  - 당신의 하루 평균 노동 시간은 몇시간인가요?
  - 당신의 하루 평균 쉬는 시간은 몇시간인가요? 운동, 독서, 개인 시간, 미디어 기기 사용 시간, 목욕 등을 포함합니다.
  - 일주일에 자녀와 함께하는 시간은 어느정도인가요?
Kid_Maximum_Age:
  18
Maximum_Life:
  84
Average:
  - 8 #sleep_hour
  - 40 #moving_min
  - 8 #working_hour
  - 4 #relax_hour
Out_Name: Report.xlsx

  